### ISSUE TITLE
Kernel not added when conda is multiuser as in cloudera

### ISSUE THREAD

**Issue by orboan** [scijava/scijava-jupyter-kernel#100]
I have conda installed in multiuser mode in the /opt directory, as a parcel installation done with the cloudera manager (CDH 6.3). 
Running 'conda install -c conda-forge scijava-jupyter-kernel' shows no error and it should be fine. But when I start a jupyter or jupyterlab, the scijava kernel is not shown. In 
/opt/cloudera/parcels/Anaconda/envs/scijava/share/jupyter/kernels/
there is only the python3 kernel, thus the scijava kernel directory with its json file is missing.
Found this json in another path:
/opt/cloudera/parcels/Anaconda/envs/scijava/conda-meta/scijava-jupyter-kernel-0.6.1-0.json
but making a symlink or a copy from this to the previous directory (where the python3 kernel json is located) makes the jupyter launcher tab appear totally blank and the regular jupyter notebook shows a "kernel error".
So what is the problem here? 
Kind regards

**Comment by orboan** [comment]
By the way I need to confirm that the installation of scijava is working perfectly fine in a conda single user installation, that I had before, in the same machine (Centos 7), where in $HOME/anaconda3/envs/scijava/share/jupyter/kernels/ it showed the python3 and also the scijava folders.

**Comment by orboan** [comment]
All the scijava kernel jars are located in:
/opt/cloudera/parcels/Anaconda/envs/scijava/opt/scijava-jupyter-kernel/
and they look that they are properly referenced in 
/opt/cloudera/parcels/Anaconda/envs/scijava/conda-meta/scijava-jupyter-kernel-0.6.1-0.json

**Comment by orboan** [comment]
Found that as a root I get:
```
# jupyter kernelspec list
Available kernels:
  scijava    /root/.local/share/jupyter/kernels/scijava
  python3    /opt/cloudera/parcels/Anaconda/envs/scijava/share/jupyter/kernels/python3
```
but as a regular user (in the scijava env):
```
$  jupyter kernelspec list
Available kernels:
  python3    /opt/cloudera/parcels/Anaconda/envs/scijava/share/jupyter/kernels/python3
```
This looks like the scijava kernel is not installed in multiuser mode, as when installed as root, instead of being installed in multiuser mode in the /opt directory, it installs as single user mode taking root as the user, which is very bad.

**Comment by imagejan** [comment]
@orboan thanks for reporting!

Note that the [ImageJ tutorial notebooks](https://github.com/imagej/tutorials/tree/master/notebooks) use a native `beakerx` Groovy kernel since a few years. I am not sure how well this component here is maintained still...

@orboan can `beakerx` be an alternative for you?

**Comment by ctrueden** [comment]
The scijava-jupyter-kernel project is being retired in favor of other solutions like [IJava](https://github.com/SpencerPark/IJava) and [BeakerX](http://beakerx.com).
