### ISSUE TITLE
Move to scijava org

### ISSUE THREAD

**Issue by hadim** [scijava/scijava-jupyter-kernel#60]
To be more consistent.

**Comment by hadim** [comment]
@ctrueden once moved to the scijava org, would you consider shipping the kernel by default with Fiji?

**Comment by ctrueden** [comment]
> would you consider shipping the kernel by default with Fiji?

Sure, if that is what you want. As usual, you can make your decision based on the [Fiji contribution requirements](https://imagej.net/Fiji/Contribution_requirements). I think SciJava Jupyter Kernel is well in line with them already. One question to discuss might be whether it brings in too many MBs worth of dependencies, but I am not extremely concerned about that. In the (not-too-near) future, I think ImageJ will ultimately have a more granular plugin installation workflow which mitigates that issue.

**Comment by hadim** [comment]
Great. I think that would be a good idea. Let's do that after the move.

About the deps, the big ones are coming from Beakerx and should be removed​ from the base kernel at some point (I am pushing on that direction).

**Comment by hadim** [comment]
What needs to be done:

1. Move the GitHub repo (only @ctrueden can do that)
2. Rename all the repo URLs to `https://github.com/scijava/scijava-jupyter-kernel`
3. Update the conda forge repo: https://github.com/conda-forge/scijava-jupyter-kernel-feedstock
4. Update the Wiki page https://imagej.net/Scijava_Jupyter_Kernel
5. Add the dependency into the Fiji `pom.xml`: (only @ctrueden can do that)

**Comment by hadim** [comment]
@ctrueden if you can take care of 1, I have free time until tomorrow to do tasks up to 4.

Then you can do 5 whenever you want in the future.

(tell me if you think more things need to be done)

**Comment by ctrueden** [comment]
I do not have admin access to this repo, so I cannot move it. If you click Settings, can you transfer it to scijava org?

**Comment by ctrueden** [comment]
Add scijava-jupyter-kernel to the SciJava BOM: https://github.com/scijava/pom-scijava/commit/5c938a1211f167742b1d0de0b95f10ea95b1caad

**Comment by hadim** [comment]
You are admin now.

**Comment by hadim** [comment]
Thanks! I'll take care of the other stuff.

**Comment by hadim** [comment]
@ctrueden last thing, I need you to enable Travis (need to be admin for that).

**Comment by hadim** [comment]
Now done.

**Comment by ctrueden** [comment]
Looks like you got Travis enabled, eh? Great!
