### ISSUE TITLE
Autocompletion issues

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-jupyter-kernel#61]
When running `jupyter notebook` with `scijava-jupyter-kernel` 0.4.0 on Mac OSX, just typing a few characters and then <kbd>Tab</kbd> will crash the kernel. This apparently only happens _before_ the first cell was executed.

On subsequent trials, autocompletion with <kbd>Tab</kbd> seems to work, but when showing multiple options, it always displays the entire content of the cell up to the cursor position (together with the suggested completion, of course). In my trials, it once happened that the `#!` annotations at the start of the cell were erased (replaced by empty lines) by the autocompletion, but I currently cannot reproduce.

On Windows 7, scijava-jupyter-kernel get updated to version 0.4.0 without problems, but in a new notebook, the kernel is still displayed as "Scijava" instead of "SciJava" (with camel case), and hitting <kbd>Tab</kbd> leads to the entire cell contents being replaced by

```
Autocompletion does not work yet.
```

**Comment by hadim** [comment]
The first bug is fixed with dbd866a80b2571d6fb3011cbbe3e955e01cefe1e.

For the second bug, I just realized that the string returned is the entire cell and not only the current line where TAB is triggered. I'll try to improve the behavior.

On windows try to remove all your scijava kernel and reinstall it from scratch. It looks like a mix between an old installation.

**Comment by hadim** [comment]
I tried a fix for the second bug but it requires more work.

In short the `String code` returned [here]() contains all the code of the cell and `index` is the index number where TAB has been triggered. What needs to be done:

- Split the String in `List<String> lines`.
- Calculate the current line number and store it as a String.
- Calculate the index in the current line.
- Use the above in `completer.autocomplete(code, index, scriptEngine)`.

Then it should magically work.

I won't be able to fix that before few weeks probably.

**Comment by imagejan** [comment]
> On windows try to remove all your scijava kernel and reinstall it from scratch. It looks like a mix between an old installation.

You were right, I still had the old SNAPSHOT jar in my anaconda environment from previous tests, and the 0.4.0 version was installed next to it. Thanks for the hint.

> * Split the String in `List<String> lines`.

Maybe also splitting at the last space character would make sense.
Anyhow, maybe this is not even necessary, as long as the displayed choices are not repeating the whole code but just the relevant object/method/field...

**Comment by hadim** [comment]
Autocompletion has a problem with multiple lines cells. It should be fixed.

**Comment by hadim** [comment]
Fixed in d0335e37c063de2b6892fe57dc1e3ca8d5a3f8e1
