### ISSUE TITLE
Cannot add scijava-jupyter-kernel under OSX

### ISSUE THREAD

**Issue by Meyenhofer** [scijava/scijava-jupyter-kernel#62]
Running OSX Sierra 10.12.5 (16F73) 

I downloaded a fresh Fiji, then Help > Updated
then I added the update site (Manage Sites) and closed the update sites dialog. But then the ImageJ Updater does not have any changes to apply (Apply button is grayed out). 
So even though the update site is selected, the updater does not seem to recognize what jars it should download.

**Comment by imagejan** [comment]
That's right, http://sites.imagej.net/Scijava-jupyter-kernel/ has nothing than a single `db.xml.gz`, no jar file available.

@Meyenhofer did you try installing via anaconda, without using Fiji?

@hadim is installation via Fiji an intended use case, or was it abandoned now that the kernel is a scijava component?

**Comment by Meyenhofer** [comment]
@imagejan 
yes, that works.
![image](https://cloud.githubusercontent.com/assets/729273/26627289/35941700-45fa-11e7-9e17-8eb58449530a.png)


:-)

However I still stick to my version (https://github.com/hadim/scijava-jupyter-kernel/issues/34#issuecomment-296998143) of the setup

**Comment by hadim** [comment]
At the moment, I didn't upload the package to update site. I would like to setup automatic upload from Travis. Any help with that would be appreciated

In the meantime, if someone wants to take manually update the package to the update site, I can give you the password.

**Comment by ctrueden** [comment]
Better: I can add users to the WebDAV authorization list for that update
site. Just let me know who.

**Comment by hadim** [comment]
I am gonna upload manually to update site until the kernel is integrated to Fiji.

**Comment by hadim** [comment]
For now it's not possible to upload the kernel to an update site (and it's gonna be the same issue if we decide to ship the kernel by default with Fiji) because Beakerx dependencies have conflicts.

![screenshot from 2017-06-02 18-46-27](https://cloud.githubusercontent.com/assets/528003/26747680/7945e862-47c5-11e7-9351-54e74f650121.png)

I know the Beakerx folks are planning to remove all the heavy and unnecessary deps from the base kernel at some point. Hope it's gonna happen soon.

**Comment by hadim** [comment]
See #66

**Comment by hadim** [comment]
I was able to fix the dep issue and upload the kernel to the Scijava-jupyter-kernel update site (thanks @ctrueden again).
