### ISSUE TITLE
Ship to Fiji

### ISSUE THREAD

**Issue by hadim** [scijava/scijava-jupyter-kernel#66]
Manual upload to update site or ship by default with Fiji. In any case, we need to wait for Beakerx folks to clean the dependencies they are using in the base kernel.

**Comment by ctrueden** [comment]
> we need to wait for Beakerx folks to clean the dependencies they are using in the base kernel.

FYI, if there are features of the base kernel which need a dep, but which you know we don't need—therefore making that dep unnecessary for our particular use case—you can add `<exclusions>` so those deps do not get included when doing Maven-based things.

**Comment by hadim** [comment]
Good idea!
