### ISSUE TITLE
Deprecate installation from Fiji

### ISSUE THREAD

**Issue by hadim** [scijava/scijava-jupyter-kernel#76]
What do you think guys?

ping @ctrueden @kephale @imagejan @awalter17 @stelfrich

**Comment by ctrueden** [comment]
I am all for maintaining less things. Let's do Python-based software the Pythonic way, and encourage everyone to use (Ana)conda.

**Comment by hadim** [comment]
Done with 00a19603133f18014d1fa7c6d6b779a1da152cd9

(we can still revert it if needed)
