### ISSUE TITLE
Kernel shown in list of kernels but not in jupyterhub

### ISSUE THREAD

**Issue by pfisterer** [scijava/scijava-jupyter-kernel#79]
I wanted to install scijava-jupyter-kernel but it is not shown in jupyterhub. I've tried to install it in a separate conda environment and in the root environment (using 'fresh' virtual machines on Debian 9). 

In the case of using the root environment, I was able to see the scijava-jupyter-kernel:

```
root@jupyter:~# jupyter-kernelspec list
Available kernels:
  python3        /usr/local/lib/python3.5/dist-packages/ipykernel/resources
  scijava        /root/.local/share/jupyter/kernels/scijava
  cling-cpp14    /usr/local/share/jupyter/kernels/cling-cpp14
```
 However, when executing `jupyterhub` or `jupyter notebook`, I only see the following kernels:

<img width="291" alt="screen shot 2017-08-22 at 09 56 11" src="https://user-images.githubusercontent.com/302635/29554633-2a237282-8720-11e7-8cf6-05c9b1d7f8f7.png">

Any ideas what I'm doing wrong?

Thanks,
Dennis

**Comment by ctrueden** [comment]
@hadim @hanslovsky Any ideas?

**Comment by hadim** [comment]
Hello @pfisterer ,

When it is said *root env* in the README, it does not mean *root linux user* but the *root conda env*. Here you have installed the kernel using the root user (which could be a security issue). And I could bet that jupyter can't access to the files inside the kernel directory `/root/.local/share/jupyter/kernels/scijava`.

Please try to create a [conda environment](https://conda.io/docs/using/envs.html) and then install the kernel from there.

Then you have two options:

1. Start the kernel from your custom conda env and enjoy your Scijava kernel.
2. Go back to the root conda env, install [`nb_conda_kernels`](https://github.com/Anaconda-Platform/nb_conda_kernels) and start jupyter from the root env. All the kernels inside your envs should be detected and shown in the dropdown list.

Let me know if it works for you.

Also, any PRs to improve the README about that is welcome :-)

**Comment by hanslovsky** [comment]
@pfisterer
I do not have an immediate guess as to what went wrong but maybe you can help us dig deeper by giving us additional information:
 - What exact steps did you take to create the environments/install the kernels? If you have the command history, please post here.
 - What is your environment, most importantly `PATH` and `PYTHONPATH`? Please add the outputs of these commands:
    - `env`
    - `echo $PYTHONPATH`
    - `echo $PATH`
    - `which jupyter`
    - `which jupyter-kernelspec`
 - Where are your conda environments located (only the relevant ones, including root): `conda env list`.

**Comment by hadim** [comment]
@pfisterer is your problem solved? Please feel free to reopen if needed.

**Comment by pfisterer** [comment]
Thank you all for the support - I did not have time to test your suggestions until today. I'm running jupyterhub with standard Unix system users. So each instance of `jupyterhub-singleuser` is spawned using the user id of the user that is logging in. 

So I think the cause of the problem is that the kernel has not been installed to `/usr/local/share/jupyter/kernels/`. Making `/root/.local/share/jupyter/kernels/scijava/` world-readable and linking this directory to `/usr/local/share/jupyter/kernels/scijava` (using `ln -s /root/.local/share/jupyter/kernels/scijava/ scijava`) worked for me (using the root conda env of user root).

However, this does not seem to be a good solution for this issue... Any ideas how to do this in a better way?

**Comment by ctrueden** [comment]
@pfisterer For what it's worth, I have the scijava-jupyter-kernel working with mybinder.org (which is built on JupyterHub); see [imagej/tutorials](https://github.com/imagej/tutorials), and the [environment.yml](https://github.com/imagej/tutorials/blob/735400d2b8c16a48e9130e9de48e311937723392/environment.yml) specifically.

Does that help at all?

**Comment by pfisterer** [comment]
@ctrueden I'll give this a try. Thank you all for supporting me!
