### ISSUE TITLE
Java 9?

### ISSUE THREAD

**Issue by pdeitel** [scijava/scijava-jupyter-kernel#84]
Any plans for Java 9/JShell support?

**Comment by ctrueden** [comment]
@pdeitel No one has had time to look into yet it, although JShell is certainly a nice development, and we do want to improve the support for the Java kernel. See also #80.

**Comment by pdeitel** [comment]
Thanks Curtis. Any general timeframe? I am looking into options for a course I'll be teaching in April or May.

**Comment by ctrueden** [comment]
@pdeitel Could you describe your requirements a bit? You're hoping to have JShell in Jupyter, essentially? Why is this better than using e.g. Groovy or Jython or CPython?

**Comment by pdeitel** [comment]
I am teaching an online Java 9 class. I am thinking that I can save a LOT of time by demonstrating various features in a notebook based environment. I've been doing a lot recently with IPython in Jupyter and really like it. Thinking I could customize one of the existing Jupyter Docker containers with everything my students would need to simplify getting up and running for the course.

**Comment by ctrueden** [comment]
Did you try out https://github.com/eiswind/jupyter-kernel-jshell ?

If it is not good, and there are no other existing good options for JShell in a Jupyter notebook, I can try to find time for my group to work on the SciJava script framework's Java support before April. Let us know!

**Comment by pdeitel** [comment]
I'll keep poking around, but I would absolutely be interested in a Jupyter kernel with Java 9 support, JShell support or both.

**Comment by pdeitel** [comment]
And I sincerely appreciate your wilingness to do that!

**Comment by pdeitel** [comment]
Just a follow up on this as I am now actively investigating Java kernels for potential use in our books. Does this kernel support the latest Java version (12)? If so, how do I make the kernel use it as it appears to be using Java 8 right now? Thanks!

**Comment by ctrueden** [comment]
@pdeitel Sorry for the lack of reply. I hope you found an appropriate kernel to use. You never answered my question about the `jupyter-kernel-jshell`—did it work for you? I think a JShell-based kernel is going to be better than this one, especially since our current plan is to [retire this kernel in favor of always using the BeakerX kernels directly](https://forum.image.sc/t/imagej-jupyter-notebooks-updated-imagej-python-retiring-the-scijava-jupyter-kernel/21845).

**Comment by ctrueden** [comment]
There is now a kernel [IJava](https://github.com/SpencerPark/IJava) which is built on JShell.
