### ISSUE TITLE
Install additional packages for Python 

### ISSUE THREAD

**Issue by drivenbyentropy** [scijava/scijava-jupyter-kernel#86]
Hi, 

First of all, amazing work you are doing here :). This might be a trivial question and might have been mentioned somewhere already, but I did not find any information regarding this so I thought I would ask:

Is there a way to install additional packages for python? Specifically, `numpy` and `matplotlib`? If I add these packages through the Anaconda Navigator, I still get the following error: 
```python
#!python
import numpy as np
import matplotlib.pyplot as plt

#[..code here..]
```

```
Traceback (most recent call last):
  File "dummy.py", line 2, in <module>
ImportError: No module named numpy
```

My apologies if this is a duplicate, this is new territory for me.

Thanks!

**Comment by ctrueden** [comment]
@drivenbyentropy The Python mode of the SciJava Jupyter Kernel uses Jython under the hood (all of the SciJava script languages are built on top of the JVM). You can read about how Jython finds modules [here](http://www.jython.org/jythonbook/en/1.0/ModulesPackages.html#module-search-path-and-loading).

Unfortunately, Jython does not support CPython extensions written in C, like numpy. (See the [FAQ](https://wiki.python.org/jython/JythonFaq/GeneralInfo#Is_Jython_the_same_language_as_Python.3F)). There is an effort called [JyNI](http://jyni.org/) underway to remedy this, allowing numpy to work with Jython, but scipy only partially works, and scikit-image functions largely do not work yet.

Another option exists for using CPython native modules: call SciJava from Python via pyjnius. There are Python notebooks demonstrating this at:

* https://github.com/imagej/tutorials/blob/11bc376ed81b43c6abf984c6ca7740aaea62c8aa/notebooks/3_-_Advanced_usage/3_-_ImgLyb_-_ImgLib2_-_with_-_scikit-image.ipynb
* https://github.com/CellProfiler/notebooks/blob/95a2558060075b0c8c9ad254413fac8dacfc2d12/imagej_pyjnius_demo.ipynb

It is still experimental, but we are actively working on improving the usability of these sorts of notebooks. If all you care about is Python+Java, I think this is a nice way to go.

A third option is the [ImageJ Server](https://github.com/imagej/imagej-server). A notebook demonstrating that is at:

* https://github.com/CellProfiler/notebooks/blob/95a2558060075b0c8c9ad254413fac8dacfc2d12/imagej_server_demo.ipynb

**Comment by drivenbyentropy** [comment]
Thanks for the explanation @ctrueden, this clears things up. I will look into these solutions and see if I can adopt them for my purposes.
