### ISSUE TITLE
Java kernel Jupyter-Notebook didn't fail on illegal Java Generic Code

### ISSUE THREAD

**Issue by lostdinar2** [scijava/scijava-jupyter-kernel#88]
Hello.I am a beginner for jupyter.I install jupyter scijava kernel and write some piece of illegal code for Java Generics.In Netbeans this code fails with java.lang.RuntimeException.But it didn't fail on Jupyter-Notebook.

List<? super Integer> list=new ArrayList<Object>();
list.add(new Object());
Out 17:true

I guess something is wrong.Maybe a bug or I do something wrong.
Thanks.

**Comment by ctrueden** [comment]
Note though that Java is not working as script language in notebooks yet. See #80. But BeanShell and Groovy are very close syntactically.
