### ISSUE TITLE
Problem with jython-shaded-2.7.0

### ISSUE THREAD

**Issue by gildasmorvan** [scijava/scijava-jupyter-kernel#89]
Dear scijava-jupyter-kernel developers,

I encountered a problem with scijava kernel related to jython-shaded-2.7.0. When executing my code with that version of jython I had the following error when calling the constructor of a superclass (coded in java):
```
TypeError: Default constructor failed for Java superclass
```
Since my code was running well outside jupyter with jython 2.7.1 I replaced  jython-shaded-2.7.0.jar by  jython-shaded-2.7.1.jar that I found [there](http://central.maven.org/maven2/org/scijava/jython-shaded/2.7.1/). And now everything runs normally 😀

So I think it would be a good idea to upgrade  jython-shaded in scijava kernel. 

Note: my code can be found [there](https://github.com/gildasmorvan/similar2logo/blob/master/similar2logo-examples/src/main/doc/notebooks/Python/Python%20Passive%20turtle%20example.ipynb).

Best regards,

Gildas

**Comment by gildasmorvan** [comment]
Update: When looking at the pom of the project, I realize the problem is related to the [scripting-jython](https://github.com/scijava/scripting-jython) project. I am opening an issue there.

**Comment by ctrueden** [comment]
Thanks @gildasmorvan. I'm closing this issue here in favor of scijava/scripting-jython#10.
