### ISSUE TITLE
groovy.lang.MissingPropertyException when trying to run seperate code blocks

### ISSUE THREAD

**Issue by lostdinar2** [scijava/scijava-jupyter-kernel#90]
Hello.I have an issue with combining code blocks in SciJava. [Jupyter Notebook documentation](http://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Running%20Code.html) says that "Each notebook is associated with a single kernel."But İn scijava following code blocks is throwing the exception:

`In [1]:int x=4;
In [2]:System.out.println(x);`

> [ERROR] null
> groovy.lang.MissingPropertyException: No such property: x for class: Script1
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
> 	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
> 	at Script1.run(Script1.groovy:1)
> 	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:303)
> 	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:122)
> 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
> 	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
> 	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
> 	at org.scijava.jupyter.kernel.evaluator.Worker.run(Worker.java:108)
> 	at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

I expecting that kernel can run separate code blocks just like Python kernel.But it throws an error. Am I missing something?

**Comment by imagejan** [comment]
In Groovy (which is the default language when using the SciJava Jupyter Kernel), definitions like `int x=4` or `def x=4` won't have the correct scope.

You can however leave away the `int`, then it works:

In [1]:
```
x=4
```

In [2]:
```
System.out.println(x)
```

(Note that for the second cell, simply having `x` instead of the `System.out.println` statement will also print the output.)

**Comment by lostdinar2** [comment]
Thanks a lot.
