### ISSUE TITLE
How to install third party dependencies or jars in a jupyter notebook?

### ISSUE THREAD

**Issue by alonsopg** [scijava/scijava-jupyter-kernel#92]
I recently installed the kernel for java. How can I install a library in order to start using it from the jupyter notbeook?

**Comment by ctrueden** [comment]
@alonsopg Have you tried the BeakerX kernels? There is one for Java. You can use [classpath magic](https://github.com/twosigma/beakerx/blob/master/doc/groovy/ClasspathMagicCommands.ipynb) to dynamically load whatever libraries you want from remote repositories.

This SciJava Jupyter Kernel is built on BeakerX, but an older version. We are in the process of migrating all SciJava notebooks away from the SciJava Jupyter Kernel, in favor of the regular BeakerX kernels. As such, this kernel will be deprecated soon. Unless you have a reason we didn't think of for why SJJK is still helpful on top of plain BeakerX?
