### ISSUE TITLE
scijava installation on mac os mojave

### ISSUE THREAD

**Issue by sweattej** [scijava/scijava-jupyter-kernel#94]
I have tried to install scijava using  "conda install  -c conda-forge scijava-jupyter-kernel" on three macs running mojave. The machines are two imacs and a macbook pro. On each mojave machine I  attempted the install using a  newly installed, updated anaconda. I've installed scijava on two macbook pros running sierra without issue. Also installed successfully on a linux mint 19 machine.  All three mojave installs fail consistently, see attached terminal output.
![image](https://user-images.githubusercontent.com/8423191/50345884-8d47ad80-04fe-11e9-8ac5-63e7d25e6a94.png)
Thanks,

**Comment by ctrueden** [comment]
The scijava-jupyter-kernel project is being retired in favor of other solutions like [IJava](https://github.com/SpencerPark/IJava) and [BeakerX](http://beakerx.com).
